imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    list:
      path: /v2/labor/workweek-configs
      method: GET
      auth: true
      docs: Returns a list of `WorkweekConfig` instances for a business.
      pagination:
        cursor: $request.cursor
        next_cursor: $response.cursor
        results: $response.workweek_configs
      display-name: ListWorkweekConfigs
      request:
        name: WorkweekConfigsListRequest
        query-parameters:
          limit:
            type: optional<integer>
            docs: >-
              The maximum number of `WorkweekConfigs` results to return per
              page.
          cursor:
            type: optional<string>
            docs: A pointer to the next page of `WorkweekConfig` results to fetch.
      response:
        docs: Success
        type: root.ListWorkweekConfigsResponse
      examples:
        - response:
            body:
              workweek_configs:
                - id: FY4VCAQN700GM
                  start_of_week: MON
                  start_of_day_local_time: '10:00'
                  version: 11
                  created_at: '2016-02-04T00:58:24Z'
                  updated_at: '2019-02-28T01:04:35Z'
              cursor: 2fofTniCgT0yIPAq26kmk0YyFQJZfbWkh73OOnlTHmTAx13NgED
              errors:
                - category: API_ERROR
                  code: INTERNAL_SERVER_ERROR
                  detail: detail
                  field: field
    get:
      path: /v2/labor/workweek-configs/{id}
      method: PUT
      auth: true
      docs: Updates a `WorkweekConfig`.
      path-parameters:
        id:
          type: string
          docs: The UUID for the `WorkweekConfig` object being updated.
      display-name: UpdateWorkweekConfig
      request:
        name: UpdateWorkweekConfigRequest
        body:
          properties:
            workweek_config:
              type: root.WorkweekConfig
              docs: The updated `WorkweekConfig` object.
      response:
        docs: Success
        type: root.UpdateWorkweekConfigResponse
      examples:
        - path-parameters:
            id: id
          request:
            workweek_config:
              start_of_week: MON
              start_of_day_local_time: '10:00'
              version: 10
          response:
            body:
              workweek_config:
                id: FY4VCAQN700GM
                start_of_week: MON
                start_of_day_local_time: '10:00'
                version: 11
                created_at: '2016-02-04T00:58:24Z'
                updated_at: '2019-02-28T01:04:35Z'
              errors:
                - category: API_ERROR
                  code: INTERNAL_SERVER_ERROR
                  detail: detail
                  field: field
  source:
    openapi: openapi/openapi.yaml
